<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

        <div class="row">
            <div class="col-md-6">
                <?php echo DwForm::text('sucursal.sucursal', array('class'=>'input-xlarge input-required show-error'), NULL, 'Nombre de la ciudad'); ?>
            </div>
        </div>
        
        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Guardar ciudad'); ?>
                <?php echo DwForm::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>