<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

        <div class="row">
            <div class="col-md-6">
                <?php echo DwForm::hidden('sucursal.id', NULL, $sucursal->id); ?>
                <?php echo DwForm::hidden('sucursal.ciudad_id', NULL, $sucursal->id); ?>
                
                <?php echo DwForm::text('sucursal.sucursal', array('class'=>'input-xlarge input-required show-error'), $sucursal->sucursal, 'Nombre de la sucursal'); ?>
            </div>
        </div>
            
        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Guardar sucursal'); ?>
                <?php echo DwForm::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>