<header class="navbar navbar-inverse navbar-fixed-top user-nav" role="navigation" id="slide-nav">
    
    <div class="container">
        
        <div class="navbar-header hidden-xs">            
            <?php echo DwHtml::link('dashboard', DwHtml::img("upload/empresa/".APP_CLIENT_LOGO, APP_NAME, array('style'=>'height: 40px; margin-top: 1%;')), '' , FALSE); ?> <a href="">&nbsp;&nbsp;</a> <a href="#" style="color:#FFF; font-size:18px; font-weight:bold font-family:'Comic Sans MS'"><?php echo APP_NAME; ?></a>                
        </div>
        
        <div class="navbar-header visible-xs">
            <a class="navbar-toggle"> 
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </a>
            <?php echo DwHtml::link('dashboard', APP_NAME, array('class'=>'navbar-brand'), '' , FALSE); ?>           
        </div>
        
        <div id="slidemenu" class="visible-xs"> 
            
            <div class="text-center navbar-form" style="height: 50px;">
                <?php echo DwHtml::link('dashboard', DwHtml::img("upload/empresa/".APP_CLIENT_LOGO, APP_NAME, array('style'=>'height: 35px; margin-top: 1.5%')), '' , FALSE); ?>                
            </div>
            <div class="slide-navbar">                                
                <?php echo DwMenu::phone(); ?>
                <ul class="nav navbar-nav">                                    
                    <li class="divider"></li>
                    <li><?php echo DwHtml::link('sistema/mi_cuenta/', 'Mi cuenta'); ?></li>
                    <li class="divider"></li>                    
                    <li><?php echo DwHtml::link('login/salir/', 'Salir', array('class'=>'no-load'), 'fa-power-off', FALSE); ?></li>
                </ul>

            </div>
        </div>
        
        <div class="pull-right hidden-xs">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a id="encabezado-usuario" name="encabezado-usuario" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"> 
                        <?php echo DwHtml::img("upload/personas/".Session::get('fotografia'), "", array('id'=>'img-usuario-actual')); ?>&nbsp;&nbsp;
                        <?php echo Session::get('login'); ?> <b class="caret"></b>
                    </a>
                    
                    <ul class="dropdown-menu" role="menu" style="left: auto; right: 0 !important">                                
                        <li><?php echo DwHtml::link('sistema/mi_cuenta/', 'Mi cuenta'); ?></li>
                        <li class="divider"></li>
                        <li><?php echo DwHtml::link('sistema/login/salir', 'Salir', array('class'=>'no-load'), 'icon-off', FALSE); ?></li>                
                    </ul>
                </li>
            </ul>
        </div>       
        
    </div>            
    
</header>