<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>
    
        <div class="row">    
            <div class="col-md-2">
                <?php echo DwForm::hidden('acuentas.id', NULL, $acuentas->id); ?>

                <?php echo DwForm::text('acuentas.codigo_cta', array('class'=>'input-small input-required show-error'), $acuentas->codigo_cta, 'Código'); ?>
            </div>
            <div class="col-md-8">
                <?php echo DwForm::text('acuentas.nombre_cta', array('class'=>'input-xlarge input-required show-error'), $acuentas->nombre_cta, 'Nombre de la cuenta'); ?>
            </div>
        </div>

        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Guardar Cuenta'); ?>
                <?php echo DwForm::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>
</div>
