<?php View::flash(); ?>

<div class="container shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php View::partial('subnav/usuario/principal', FALSE, array('id'=>$usuario->id)); ?>
    
    <?php echo DwForm::open(); ?>
    
    <ul class="nav nav-tabs hidden-xs">
        <li class="active"><a href="#tab1" data-toggle="tab">Información personal</a></li>
        <li><a href="#tab2" data-toggle="tab">Información de la cuenta</a></li>
        <li><a href="#tab3" data-toggle="tab">Cargar imágen</a></li>
    </ul>
    <ul class="nav nav-pills nav-stacked visible-xs">    
        <li class="active"><a href="#tab1" data-toggle="tab">Información personal</a></li>
        <li><a href="#tab2" data-toggle="tab">Información de la cuenta</a></li>
        <li><a href="#tab3" data-toggle="tab">Cargar imágen</a></li>
    </ul>

    <div class="tab-content">
        
        <div class="tab-pane active" id="tab1">
            
            <div class="row">
                <div class="col-md-6">                    
                    <?php echo DwForm::text('persona.nombre', array('class'=>'input-required'), $usuario->nombre, 'Nombre'); ?>
                </div>
                <div class="col-md-6">
                    <?php echo DwForm::text('persona.apellido', array('class'=>'input-required'), $usuario->apellido, 'Apellido'); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-6">
                    <?php echo DwForm::email('usuario.email', array('class'=>'input-email input-required mask-email'), $usuario->email, 'Email'); ?>
                </div>       
            </div>
            
            <div class="row">
                <div class="col-md-6">
                    <?php echo DwForm::number('persona.nuip', array('class'=>'input-xxlarge input-required mask-pint show-error'), $usuario->nuip, 'No. Telefono'); ?>
                </div>
                <div class="col-md-6">
                    <?php echo DwForm::dbSelect('persona.tipo_nuip_id', 'tipo_nuip', array('params/tipo_nuip', 'getListadoTipoNuip'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), $usuario->tipo_nuip_id, 'Tipo de identificación'); ?>
                </div>
            </div>    
        </div>
        
        <div class="tab-pane" id="tab2">
            
            <div class="row">
                <div class="col-md-6">                    
                    <?php echo DwForm::text('usuario.login', array('class'=>'input-lower input-readonly'), $usuario->login, 'Usuario'); ?>
                </div>
                <div class="col-md-6">
                    <?php echo DwForm::dbSelect('usuario.perfil_id', 'perfil', array('sistema/perfil', 'getListadoPerfil', Perfil::ACTIVO), NULL, array('class'=>'input-xxlarge input-required input-lists'), $usuario->perfil_id, 'Perfil'); ?>
                </div>
            </div>

            <div class="row">
                <?php if(APP_OFFICE) { ?>
                <div class="col-md-6">
                    <?php echo DwForm::dbSelect('usuario.sucursal_id', array('sucursal', 'ciudad'), array('config/sucursal', 'getListadoSucursal'), array('todas'=>'Todas'), array('class'=>'input-xxlarge input-required mask-pint show-errors'), empty($usuario->sucursal_id) ? 'todas' : $usuario->sucursal_id, 'Sucursal'); ?>
                </div>
                <?php } ?>
                <div class="col-md-6">
                    <?php echo DwForm::number('usuario.datagrid', array('class'=>'input-numeric input-required mask-pint'), $usuario->datagrid, 'Cantidad de datos por página', 'Esta información se utiliza en los listados de informaciones y reportes'); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-6">
                    <?php echo DwForm::select('usuario.app_ajax', array('1'=>'On', '0'=>'Off'), array('class'=>'input-list input-required'), $usuario->app_ajax, 'App con AJAX', 'Deshabilitar para conexiones lentas'); ?>
                </div>
                <div class="col-md-6">
                    <?php echo DwForm::select('usuario.tema', $temas, array('class'=>'input-list input-required'), $usuario->tema, 'Apariencia'); ?>
                </div>
            </div>           
                        
            <div class="row">
                <div class="col-md-6">
                    <?php echo DwForm::pass('usuario.password', array('class'=>'input-pass'), '', 'Contraseña'); ?>
                </div>
                <div class="col-md-6">
                    <?php echo DwForm::pass('repassword', array('class'=>'input-repass'), '', 'Confirmación'); ?>
                </div>
            </div>
            
        </div>
        
        <div class="tab-pane" id="tab3">
            
            <div class="row fileupload-buttonbar">

                <div class="col-md-6" style="margin-bottom: 20px;">

                    <div class="row">

                        <div class="col-md-6">
                            <?php echo DwForm::upload('fotografia', array('data-to'=>PUBLIC_PATH.'sistema/usuarios/upload/', 'data-size'=>5000000, 'data-files'=>'images', 'data-success'=>'loadImg'), 'Fotografía'); ?>
                        </div>

                        <div class="col-md-6">
                            <div class="picture-profile text-center text-middle shadow-dark" style="margin: 5px auto 0px;">
                                <?php echo DwHtml::img("upload/personas/$usuario->fotografia", "Fotografía", array('id'=>'img-usuario')); ?>
                            </div>
                        </div>

                    </div>

                </div>

            </div>
            <?php echo DwForm::hidden('usuario.id', $usuario->id); ?>
            <?php echo DwForm::hidden('persona.fotografia', NULL, $usuario->fotografia); ?>
            
        </div>        
        
    </div>
    
    <div class="row">
        <div class="form-actions">
            <?php echo DwForm::send('Editar usuario'); ?>
            <?php echo DwForm::cancel(); ?>
            <?php echo DwForm::focus('usuario.nombre'); ?>            
        </div>
    </div>
   
    <?php echo DwForm::close(); ?>
    
</div>

<script type="text/javascript">
    
    function loadImg(result, input) {
        $("#persona_fotografia").val(result.name);
        $("#img-usuario").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/personas/'+result.name);                
    }
    
</script>