<?php View::flash(); ?>

<div class="account-container">

    <div class="content clearfix" style="background-color:#292929">

        <?php echo DwForm::open(); ?>

            <?php echo DwForm::focus('login'); ?>

            <noscript><h5 style="text-align: center;">¡Tu navegador no soporta Javascript!.. Activa el uso de Javascript en tu navegador.</h5></noscript>

            <div align="center" class="dw-text-center" style="width: 100%; margin: 0 auto;">
                <?php echo DwHtml::img("upload/empresa/".APP_CLIENT_LOGO, APP_CLIENT, array('style'=>'margin-top: 18px; height: 40px;'));?>
            </div>

            <br>

            <div class="container login-fields">
                
                <h5>Ingresa tu usuario y contraseña:</h5>  
                                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="field form-group">
                            <label for="login">Usuario:</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                <input type="text" id="login" name="login" value="" placeholder="Usuario" class="form-control login username-field input-required" />
                            </div>
                        </div>                        
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="field form-group">
                            <label for="password">Contraseña:</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-key"></i></span>
                                <input type="password" id="password" name="password" value="" placeholder="Contraseña" class="form-control login password-field span10 input-required"/>
                            </div>
                        </div>
                    </div>                    
                </div>
                

                <div>
                    <?php echo DwForm::hidden('mode', null, 'auth'); ?>
                </div>

                <div>
                    <?php echo DwForm::token(); ?>
                </div>

            </div>

            <div class="row">
                <div class="login-actions">
                    <div class="pull-right" style="padding-right: 20px;">
                        <?php echo DwForm::btnSubmit('Entrar', array('class'=>'btn btn-warning btn-large'), 'fa-sign-in'); ?>
                    </div>
                </div>
            </div>

        <?php echo DwForm::close(); ?>

    </div>

</div>

<div class="login-extra">
    Recuperar <?php echo DwHtml::link('#', 'contraseña', array('data-target'=>'#resetPassword', 'data-toggle'=>'modal')); ?>
</div>

<?php echo DwJs::alert('Para recuperar tu contraseña puedes contactar al administrador del sistema o contactarnos a través de los siguientes medios: ', 'subtext: E-mail: email@example.com <br /> Teléfono: 123 456 78 90', 'title: Recuperación de contraseña', 'name: resetPassword', 'icon: fa-question-sign'); ?>
